// Extracts Annexe C of the FIFA WC26 Regulations (pp. 80-97) into a TypeScript
// constant. Run via: npx tsx scripts/annexC/extract.ts
//
// Output is written to src/lib/logic/annexC.generated.ts.
//
// Format of each row in the PDF:
//   <option_number> 3<X> 3<X> 3<X> 3<X> 3<X> 3<X> 3<X> 3<X>
// Columns correspond to winners of groups [A, B, D, E, G, I, K, L].
// Each 3<X> is the third-placed team from group X that plays that winner.

import fs from 'node:fs';
import path from 'node:path';
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { PDFParse } = require('pdf-parse');

const PDF_PATH = path.join(__dirname, 'source.pdf');
const OUTPUT_PATH = path.join(__dirname, '..', '..', 'src', 'lib', 'logic', 'annexC.generated.ts');
const FIRST_PAGE = 80;
const LAST_PAGE = 97;
const TOTAL_ROWS = 495;

// Row regex: option number followed by 8 "3X" cells (X is one letter A-L).
// Tolerates arbitrary whitespace between cells.
const ROW_RE = /(?:^|\s)(\d{1,3})\s+3([A-L])\s+3([A-L])\s+3([A-L])\s+3([A-L])\s+3([A-L])\s+3([A-L])\s+3([A-L])\s+3([A-L])(?=\s|$)/g;

interface ParsedRow {
  option: number;
  cells: [string, string, string, string, string, string, string, string]; // groups for [1A,1B,1D,1E,1G,1I,1K,1L]
}

async function loadPages(): Promise<string[]> {
  const data = fs.readFileSync(PDF_PATH);
  const p = new PDFParse({ data });
  const r = await p.getText();
  return r.pages.map((pg: any) => typeof pg === 'string' ? pg : (pg.text ?? ''));
}

function parseRowsFromPages(pages: string[]): ParsedRow[] {
  const rows: ParsedRow[] = [];
  for (let i = FIRST_PAGE; i <= LAST_PAGE && i <= pages.length; i++) {
    const text = pages[i - 1];
    const matches = text.matchAll(ROW_RE);
    for (const m of matches) {
      const option = Number(m[1]);
      if (option < 1 || option > TOTAL_ROWS) continue;
      const cells: [string, string, string, string, string, string, string, string] = [
        m[2], m[3], m[4], m[5], m[6], m[7], m[8], m[9],
      ];
      rows.push({ option, cells });
    }
  }
  return rows;
}

function emitTs(rows: ParsedRow[]): string {
  const sorted = [...rows].sort((a, b) => a.option - b.option);
  const lines: string[] = [];
  lines.push('// DO NOT EDIT — generated by scripts/annexC/extract.ts');
  lines.push('// Source: FIFA World Cup 26 Regulations, Annexe C (pp. 80-97).');
  lines.push('// Each entry maps an unordered set of 8 group letters (the third-placed teams that qualified)');
  lines.push('// to the assignment of those teams to the 8 "Winner vs Best-3rd" R32 matches.');
  lines.push('// Key: sorted concatenation of the 8 group letters. Value: { winnerGroup: thirdPlaceGroup }.');
  lines.push('');
  lines.push('import type { GroupLetter } from \'@/types\';');
  lines.push('');
  lines.push('export type WinnerSlot = \'A\' | \'B\' | \'D\' | \'E\' | \'G\' | \'I\' | \'K\' | \'L\';');
  lines.push('export type AnnexCAssignment = Record<WinnerSlot, GroupLetter>;');
  lines.push('');
  lines.push('export const ANNEX_C: Readonly<Record<string, AnnexCAssignment>> = {');
  for (const row of sorted) {
    const key = [...row.cells].sort().join('');
    const [a, b, d, e, g, i, k, l] = row.cells;
    lines.push(`  '${key}': { A: '${a}', B: '${b}', D: '${d}', E: '${e}', G: '${g}', I: '${i}', K: '${k}', L: '${l}' },`);
  }
  lines.push('};');
  lines.push('');
  return lines.join('\n');
}

async function main() {
  const pages = await loadPages();
  const rows = parseRowsFromPages(pages);

  // Sanity: dedupe by option number; warn on duplicates.
  const seen = new Map<number, ParsedRow>();
  for (const r of rows) {
    const prev = seen.get(r.option);
    if (prev && JSON.stringify(prev.cells) !== JSON.stringify(r.cells)) {
      throw new Error(`Conflicting parses for Option ${r.option}: ${JSON.stringify(prev.cells)} vs ${JSON.stringify(r.cells)}`);
    }
    seen.set(r.option, r);
  }
  const unique = [...seen.values()].sort((a, b) => a.option - b.option);

  if (unique.length !== TOTAL_ROWS) {
    const missing: number[] = [];
    for (let i = 1; i <= TOTAL_ROWS; i++) if (!seen.has(i)) missing.push(i);
    throw new Error(`Expected ${TOTAL_ROWS} rows, got ${unique.length}. Missing: ${missing.slice(0, 20).join(', ')}${missing.length > 20 ? '...' : ''}`);
  }

  const ts = emitTs(unique);
  fs.writeFileSync(OUTPUT_PATH, ts);
  console.log(`Wrote ${unique.length} rows to ${OUTPUT_PATH}`);
}

main().catch(e => { console.error(e); process.exit(1); });
